apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.yaml: |
    env:
      flush_interval: 1
    service:
      flush: ${flush_interval}
      log_level: info
      http_server: on
    inputs:
      - name: tcp
        listen: 0.0.0.0
        port: 5170
        chunk_size: 32
        buffer_size: 64
        format: json
    outputs:
      - name: stdout
        match: '*'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app # == pod template: labels
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: busybox:1
          volumeMounts:
            - name: varlog
              mountPath: /var/log
        - name: fluent-bit
          image: fluent/fluent-bit:3.1.9-debug
          ports:
          - containerPort: 80
          - containerPort: 5170
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/fluent-bit.yaml
              subPath: fluent-bit.yaml
              readOnly: true
      volumes:
        - name: varlog
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort # or ClusterIP
  selector:
    app: app # == pod template: labels
  ports:
    - protocol: TCP
      name: fluent-http
      port: 80
      targetPort: 80 # == pod template: spec ports container port
      nodePort: 30080
    - protocol: TCP
      name: fluent-tcp
      port: 5170
      targetPort: 5170 # == pod template: spec ports container port
      nodePort: 30170

