apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        flush        1
        daemon       Off
        log_level    trace # error, warning, info, debug, trace
        parsers_file parsers.conf
        plugins_file plugins.conf
        http_server  Off
        http_listen  0.0.0.0
        http_port    2020
        storage.metrics on # /api/v1/storage
        # storage.path /tmp/storage
        # storage.sync normal
        # storage.checksum off
        # storage.backlog.mem_limit 5M

    [INPUT]
        name   tcp
        listen 0.0.0.0
        port   5170
        format json

    [INPUT]
        name              forward
        listen            0.0.0.0
        port              24224
        buffer_chunk_size 1M
        buffer_max_size   6M

    [OUTPUT]
        name  stdout
        match *
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app # == pod template: labels
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: busybox:1
          args:
          - /bin/sh
          - -c
          - >
            i=0;
            while true;
            do
              message=$(printf '{"level":"INFO", "message":"Log number %d", "timestamp":"%s"}\n' "$i" "$(date)")
              echo "$message"
              echo "$message" | nc localhost 5170
              i=$((i+1));
              sleep 5;
            done
        - name: python
          image: fluent-logger:0.1.0
          ports:
            - containerPort: 80
        - name: fluent-bit
          image: fluent/fluent-bit:3.1.9-debug
          ports:
            - containerPort: 5170
            - containerPort: 24224
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
              readOnly: true
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort # or ClusterIP
  selector:
    app: app # == pod template: labels
  ports:
    - protocol: TCP
      name: fluent-tcp
      port: 5170
      targetPort: 5170 # == pod template: spec ports container port
      nodePort: 30170
    - protocol: TCP
      name: fluent-forward
      port: 24224
      targetPort: 24224 # == pod template: spec ports container port
      nodePort: 30224
    - protocol: TCP
      name: fluent-app
      port: 80
      targetPort: 80 # == pod template: spec ports container port
      nodePort: 30080

